### ISSUE TITLE
Schedule Spider

### ISSUE THREAD

**Issue by trent-howard** [zootytooty/ScrapeFromTheApe#1]
Run every 1-2days to collect new gigs

Perhaps we could turn this into a scheduled lambda?

https://blog.vikfand.com/posts/scrapy-fargate-sls-guide/
https://medium.com/@kagemusha_/scraping-on-a-schedule-with-aws-lambda-and-cloudwatch-caf65bc38848

**Comment by diabolical-ninja** [comment]
Addressed in #4 

Current schedule is to run every 24hrs
